### PR TITLE
add SUBGHZSPI_TransmitReceive()

### PR DESCRIPTION
**Pull request by majbthrd**
This PR makes the SUBGHZSPI HAL more consistent with the SPI HAL by providing a HAL_SUBGHZSPI_TransmitReceive() function.  This change has the added benefit of simplifying the existing HAL_SUBGHZSPI_Transmit() and HAL_SUBGHZSPI_Receive() functions (which previously were duplicates of what was effectively the same source code).

Also, the assorted spelling errors of "trough" are replaced with "through".

### CODE REVIEW

**Comment by ASELSTM** [comment]
ST Internal Reference: 133119

**Comment by ASELSTM** [comment]
Hi @majbthrd,

The submitted changes have been forwarded to our development teams for deeper analysis. We will get back to you as soon we have updates.

With regards,

**Comment by ASELSTM** [comment]
Hi, 

Our development team want to get more information about the need of your request. In fact, `HAL_SUBGHZSPI_TransmitReceive()`  is not a user API it is rather used internally by our development team. Modification or update on these API are requested by our internally. The SUBGHZ middleware given by ST is the interface directly usable by a end user. 

Would you thus please give us more details about your request. 

With regards,

**Comment by majbthrd** [comment]
This is now a year old; it is not worth the hassle.

**Pull request closed without merging**
